
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_DER = 4;
  public static final int CHAR = 53;
  public static final int POR = 9;
  public static final int IMPRIMIR = 18;
  public static final int VARDOUBLE = 58;
  public static final int ENTERO = 11;
  public static final int DIFERENTE = 36;
  public static final int CHR_IZQ = 21;
  public static final int DOSPT = 48;
  public static final int COR_DER = 6;
  public static final int FOR = 52;
  public static final int WRITE = 16;
  public static final int AND = 38;
  public static final int EJEY = 27;
  public static final int EJEX = 26;
  public static final int IGUAL = 24;
  public static final int OR = 37;
  public static final int IGUALDAD = 31;
  public static final int COMMA = 44;
  public static final int BOOLFAL = 42;
  public static final int DIV = 10;
  public static final int VARCHAR = 55;
  public static final int MAIN = 19;
  public static final int UMENOS = 13;
  public static final int ID = 23;
  public static final int REVALUAR = 14;
  public static final int RDO = 51;
  public static final int EOF = 0;
  public static final int DECIMAL = 12;
  public static final int PRUEBA = 54;
  public static final int GBARRAS = 30;
  public static final int error = 1;
  public static final int DESIF = 40;
  public static final int CADENA = 15;
  public static final int NEGACION = 43;
  public static final int MENOS = 8;
  public static final int MAYOR_QUE = 33;
  public static final int GLOBAL = 28;
  public static final int PAR_IZQ = 3;
  public static final int CHR_DER = 22;
  public static final int VOID = 20;
  public static final int ENCICLADO = 39;
  public static final int VARBOOL = 56;
  public static final int TITLE = 50;
  public static final int RCASE = 46;
  public static final int PUNTO = 17;
  public static final int GLOBALM = 29;
  public static final int VARSTRING = 57;
  public static final int MAYOR_IGUAL = 35;
  public static final int COR_IZQ = 5;
  public static final int PTCOMA = 2;
  public static final int RSWITCH = 45;
  public static final int BOOLTRUE = 41;
  public static final int MENOR_QUE = 32;
  public static final int MENOR_IGUAL = 34;
  public static final int RBREAK = 47;
  public static final int RIF = 25;
  public static final int DEFECTO = 49;
  public static final int MAS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PAR_IZQ",
  "PAR_DER",
  "COR_IZQ",
  "COR_DER",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ENTERO",
  "DECIMAL",
  "UMENOS",
  "REVALUAR",
  "CADENA",
  "WRITE",
  "PUNTO",
  "IMPRIMIR",
  "MAIN",
  "VOID",
  "CHR_IZQ",
  "CHR_DER",
  "ID",
  "IGUAL",
  "RIF",
  "EJEX",
  "EJEY",
  "GLOBAL",
  "GLOBALM",
  "GBARRAS",
  "IGUALDAD",
  "MENOR_QUE",
  "MAYOR_QUE",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "DIFERENTE",
  "OR",
  "AND",
  "ENCICLADO",
  "DESIF",
  "BOOLTRUE",
  "BOOLFAL",
  "NEGACION",
  "COMMA",
  "RSWITCH",
  "RCASE",
  "RBREAK",
  "DOSPT",
  "DEFECTO",
  "TITLE",
  "RDO",
  "FOR",
  "CHAR",
  "PRUEBA",
  "VARCHAR",
  "VARBOOL",
  "VARSTRING",
  "VARDOUBLE"
  };
}

